<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 201, 'style_name' => 'style20', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeInOutCirc|  front-background-color |rgba(166, 78, 102, 1)| front-border-color|#b5b5b5| backend-border-color|#cccccc| || front-heading-color |#ffffff| backend-background-color |rgba(166, 78, 102, 1)| || backend-info-color |#ffffff| backend-button-color |#1a1a1a| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(144, 184, 114, 1)| || backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 0.79)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |7| flip-boxshow-spread |0| front-image-height|85| front-image-margin-top |0| front-image-margin-bottom|0| front-image-margin-left|0| front-image-margin-right|0| || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |500| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || flip-col-border-size|1| flip-col-border-style|solid| flip-backend-border-size |1| flip-backend-border-style |solid| || || || || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 201, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Product Flipbox{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('back-girl.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient monte{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Product Flipbox{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-20-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-20-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-20-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-20-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 202, 'style_name' => 'style20', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(0, 115, 153, 1)| front-border-color|#e3e3e3| backend-border-color|#a44e66| || front-heading-color |#ffffff| backend-background-color |rgba(0, 115, 153, 1)| || backend-info-color |#ffffff| backend-button-color |#a44e66| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)| || backend-title-color |#ffffff||| || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 0.79)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |7| flip-boxshow-spread |0| front-image-height|85| front-image-margin-top |0| front-image-margin-bottom|0| front-image-margin-left|0| front-image-margin-right|0| || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |500| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || flip-col-border-size|1| flip-col-border-style|solid| flip-backend-border-size |1| flip-backend-border-style |solid| || || || || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 202, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Product Flipbox{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('watch.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient monte{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Product Flipbox{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-20-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-20-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-20-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-20-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 203, 'style_name' => 'style20', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(160, 118, 44, 1)| front-border-color|#e3e3e3| backend-border-color|#a44e66| || front-heading-color |#ffffff| backend-background-color |rgba(160, 118, 44, 1)| || backend-info-color |#ffffff| backend-button-color |#a44e66| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)| || backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 0.79)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |7| flip-boxshow-spread |0| front-image-height|85| front-image-margin-top |0| front-image-margin-bottom|0| front-image-margin-left|0| front-image-margin-right|0| || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |500| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || flip-col-border-size|1| flip-col-border-style|solid| flip-backend-border-size |1| flip-backend-border-style |solid| || || || || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 203, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Product Flipbox{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('bg1.png') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient monte{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Product Flipbox{#}|{#}',
    )
);
echo '<input type="hidden" name="oxilab-flip-box-data-20-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-20-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-20-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-20-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
