<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 191, 'style_name' => 'style19', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeInOutCirc| backend-background-color |rgba(158, 49, 247, 1)| backend-info-color |#e8e8e8| backend-button-color |#ffffff| backend-button-hover-color |#f01616| backend-title-color |#ffffff| || || || || || || || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(232, 232, 232, 0.61)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |5| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |30| || || || backend-button-info-padding-top|10| backend-button-info-padding-left |10| || || backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |15| backend-info-margin-right |15| || || flip-border-radius |5| || || || || || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 191, 'title' => '',
        'files' => '{#}|{#}{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-arrow-right').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('boy.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} {#}|{#}{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Gradient Flipbox{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-19-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-19-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-19-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-19-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 192, 'style_name' => 'style19', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc|  backend-background-color |rgba(247, 135, 8, 1)| backend-info-color |#e8e8e8| backend-button-color |#ffffff| backend-button-hover-color |#f01616| backend-title-color |#ffffff| || || || || || || || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(232, 232, 232, 0.61)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |5| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |30| || || || backend-button-info-padding-top|10| backend-button-info-padding-left |10| || || backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |15| backend-info-margin-right |15| || || flip-border-radius |5| || || || || || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 192, 'title' => '',
        'files' => '{#}|{#}{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-arrow-right').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('back-girl.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} {#}|{#}{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Gradient Flipbox{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-19-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-19-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-19-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-19-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 193, 'style_name' => 'style19', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| backend-background-color |rgba(8, 247, 84, 1)| backend-info-color |#ffffff| backend-button-color |#ffffff| backend-button-hover-color |#f01616| backend-title-color |#ffffff| || || || || || || || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(232, 232, 232, 0.61)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |5| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |30| || || || backend-button-info-padding-top|10| backend-button-info-padding-left |10| || || backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |15| backend-info-margin-right |15| || || flip-border-radius |5| || || || || || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 193, 'title' => '',
        'files' => '{#}|{#}{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-arrow-right').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('travel-2.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} {#}|{#}{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Gradient Flipbox{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-19-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-19-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-19-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-19-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';