<?php
if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 71, 'style_name' => 'style7', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(71, 81, 82, 1)| || front-icon-color |#b2cc53| || front-heading-color |#ffffff| backend-background-color |rgba(17, 142, 214, 1)| || backend-info-color |#ffffff| backend-button-color |#3b3b3b| || backend-button-hover-color |#ffffff||| front-info-color |#ffffff| || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(237, 220, 220, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |5| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |30| front-icon-width |60| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |8| backend-padding-left |8| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |8| backend-info-padding-bottom |8| backend-info-padding-left |8| backend-info-padding-right |8| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| || backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 71, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}BUSINESS{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-copyright').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.{#}|{#} flip-box-backend-button-text {#}|{#}+ View Application{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Certificate in Business Administration.{#}|{#} {#}|{#}{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-7-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-7-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-7-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-7-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 72, 'style_name' => 'style7', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(142, 179, 22, 0.85)| || front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(255, 255, 255, 1)| || backend-info-color |#61780c| backend-button-color |#61780c| || backend-button-hover-color |#61780c||| front-info-color |#ffffff| || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(237, 220, 220, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |5| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |30| front-icon-width |60| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |8| backend-padding-left |8| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |8| backend-info-padding-bottom |8| backend-info-padding-left |8| backend-info-padding-right |8| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| || backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 72, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Media{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-copyright').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('bg1.png') . '{#}|{#} flip-box-backend-desc {#}|{#}This burgeoning field of study is captured in our certificate program. With courses spanning a wide range of topics, you will get experience writing for many different audiences{#}|{#} flip-box-backend-button-text {#}|{#}+ View Application{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Certificate in Digital Strategy and Media Writing{#}|{#} {#}|{#}{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-7-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-7-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-7-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-7-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 73, 'style_name' => 'style7', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeOutBack| front-background-color |rgba(0, 130, 181, 1)| || front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(255, 255, 255, 1)| || backend-info-color |#0082b5| backend-button-color |#3b3b3b| || backend-button-hover-color |#0082b5||| front-info-color |#ffffff| || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(237, 220, 220, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |5| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |30| front-icon-width |60| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |8| backend-padding-left |8| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |8| backend-info-padding-bottom |8| backend-info-padding-left |8| backend-info-padding-right |8| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| || backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 73, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}WooCommerce{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-copyright').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}This certificate will give a general background in national and international history, along with specific philosophy theories throughout time.{#}|{#} flip-box-backend-button-text {#}|{#}+ View Application{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} {#}|{#}{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-7-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-7-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-7-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-7-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';