<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 281, 'style_name' => 'style28', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutExpo| front-background-color |rgba(249, 249, 249, 1)| front-border-color |#d8d8d8| front-icon-color |#088fce| backend-border-color |#d8d8d8| front-heading-color |#454545| backend-background-color |rgba(249, 249, 249, 1)| || backend-info-color |#242424| backend-button-color |#ffffff| backend-button-background |rgba(8, 143, 206, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(0, 30, 112, 1)| || backend-title-color |#4a4a4a| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |220| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(250, 245, 245, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |80| front-icon-width |100| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |5| backend-padding-left |5| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |5| backend-info-padding-right |5| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |10| flip-backend-border-size |2| flip-backend-border-style |solid| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 281, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Stethoscope{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Stethoscope{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-28-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-28-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-28-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-28-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 282, 'style_name' => 'style28', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(250, 250, 250, 0.41)| front-border-color |#d11bc2| front-icon-color |#d11bc2| backend-border-color |#d8d8d8| front-heading-color |#d11bc2| backend-background-color |rgba(250, 250, 250, 0.71)| || backend-info-color |#363636| backend-button-color |#ffffff| backend-button-background |rgba(8, 143, 206, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(61, 30, 214, 1)| || backend-title-color |#303030| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |220| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(250, 245, 245, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |80| front-icon-width |100| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |5| backend-padding-left |5| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |5| backend-info-padding-right |5| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |10| flip-backend-border-size |2| flip-backend-border-style |solid| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 282, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Doctor World{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('users').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('Nature.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('Nature.jpg') . '{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Doctor World{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-28-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-28-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-28-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-28-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 283, 'style_name' => 'style28', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeOutBack| front-background-color |rgba(250, 250, 250, 0.69)| front-border-color |#f44336| front-icon-color |#f44336| backend-border-color |#d8d8d8| front-heading-color |#f44336| backend-background-color |rgba(244, 67, 54, 1)| || backend-info-color |#fcfcfc| backend-button-color |#ffffff| backend-button-background |rgba(8, 143, 206, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |#d600cb| || backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |220| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(250, 245, 245, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |80| front-icon-width |100| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |5| backend-padding-left |5| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |5| backend-info-padding-right |5| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |10| flip-backend-border-size |2| flip-backend-border-style |solid| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 283, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Medical Kit{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('cogs').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Medical Kit{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-28-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-28-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-28-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-28-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
