<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
 $styledata = Array('id' => 171, 'style_name' => 'style17', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(49, 176, 65, 1)| front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(49, 176, 65, 1)| backend-info-color |#ffffff| backend-button-color |#ad00ad| backend-button-hover-color |#ffffff| front-border-color|#31b041| backend-border-color|#71e380||| || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |210| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(242, 242, 242, 0.53)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |6| flip-boxshow-spread |0| front-padding-top|10| front-padding-left|10| front-icon-size |30| || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| flip-col-border-size|2| flip-col-border-style|solid| flip-backend-border-size |2| flip-backend-border-style |solid| || || || || || backend-padding-top |10| backend-padding-left |10| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |0| backend-info-padding-left |10| backend-info-padding-right |10| flip-border-radius |5| backend-button-size |16| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |500| backend-button-info-padding-top|10| backend-button-info-padding-left |15| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |0| backend-info-margin-right |0| custom-css |||');
$listdata = Array(
   0 => Array('id' => 1, 'styleid' => 171, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Slide Flip Icon{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolar set ament is simple dummy text and typesetting.{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-backend-button-text{#}|{#}+ Learn More{#}|{#}',
       ),
     );
echo '<input type="hidden" name="oxilab-flip-box-data-17-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-17-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-17-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-17-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 172, 'style_name' => 'style17', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(177, 83, 201, 1)| front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(177, 83, 201, 1)| backend-info-color |#ffffff| backend-button-color |#00b3b3| backend-button-hover-color |#ffffff| front-border-color|#ae5ac4| backend-border-color|#d26feb||| || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |210| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(242, 242, 242, 0.53)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |6| flip-boxshow-spread |0| front-padding-top|10| front-padding-left|10| front-icon-size |30| || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| flip-col-border-size|2| flip-col-border-style|solid| flip-backend-border-size |2| flip-backend-border-style |solid| || || || || || backend-padding-top |10| backend-padding-left |10| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |0| backend-info-padding-left |10| backend-info-padding-right |10| flip-border-radius |5| backend-button-size |16| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |500| backend-button-info-padding-top|10| backend-button-info-padding-left |15| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |0| backend-info-margin-right |0| custom-css |||');
$listdata = Array(
     0 => Array('id' => 2, 'styleid' => 172, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Slide Flip Icon{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolar set ament is simple dummy text and typesetting.{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-backend-button-text{#}|{#}Learn More{#}|{#}',
        ),
   );
echo '<input type="hidden" name="oxilab-flip-box-data-17-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-17-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-17-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-17-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 173, 'style_name' => 'style17', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(235, 113, 42, 1)| front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(235, 113, 42, 1)| backend-info-color |#ffffff| backend-button-color |#4df055| backend-button-hover-color |#ffffff| front-border-color|#eb712a| backend-border-color|#c27342| || || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |210| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(242, 242, 242, 0.53)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |6| flip-boxshow-spread |0| front-padding-top|10| front-padding-left|10| front-icon-size |30| || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| flip-col-border-size|2| flip-col-border-style|solid| flip-backend-border-size |2| flip-backend-border-style |solid| || || || || || backend-padding-top |10| backend-padding-left |10| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |0| backend-info-padding-left |10| backend-info-padding-right |10| flip-border-radius |5| backend-button-size |16| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |500| backend-button-info-padding-top|10| backend-button-info-padding-left |15| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |0| backend-info-margin-right |0| custom-css |||');
$listdata = Array(
      0 => Array('id' => 3, 'styleid' => 173, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Slide Flip Icon{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-copyright').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolar set ament is simple dummy text and typesetting{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-backend-button-text{#}|{#}+ View Application{#}|{#}',
       )
);
echo '<input type="hidden" name="oxilab-flip-box-data-17-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-17-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-17-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-17-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';