<?php
if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 101, 'style_name' => 'style10', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(190, 0, 204, 1)| front-icon-color |#be00cc| front-icon-background-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(190, 0, 204, 1)| backend-icon-color|#ffffff| backend-info-color |#ffffff| || || || || || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 235, 235, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| flip-border-radius|5| front-padding-top |10| front-padding-left |10| || front-icon-size |30| front-icon-width |60| front-icon-border-radius |30| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-icon-size |30| backend-icon-width |60| backend-icon-padding-top-bottom |10| backend-icon-padding-left-right |10| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 101, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Consectetuer Adipiscin{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Macs, PCs, tablets or phones and see up-to-date have financials. It’s online accountings softwares that’s simple.{#}|{#} flip-box-backend-icons{#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
        ),
   );
echo '<input type="hidden" name="oxilab-flip-box-data-10-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-10-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-10-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-10-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 102, 'style_name' => 'style10', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(0, 129, 143, 0.29)| front-icon-color |#ffffff| front-icon-background-color|#8b00cc| front-heading-color |#ffffff| backend-background-color |rgba(194, 194, 194, 1)| backend-icon-color|#404040| backend-info-color |#404040| || || || || || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 235, 235, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| flip-border-radius|5| front-padding-top |10| front-padding-left |10| || front-icon-size |30| front-icon-width |60| front-icon-border-radius |30| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-icon-size |30| backend-icon-width |60| backend-icon-padding-top-bottom |10| backend-icon-padding-left-right |10| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| custom-css |||');

$listdata = Array(
     0 => Array('id' => 2, 'styleid' => 102, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Adipiscin{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('boy.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Far away, behind the word consonantia there live the blind texts n which roasted parts of sentences.{#}|{#} flip-box-backend-icons{#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
        ),
 );
echo '<input type="hidden" name="oxilab-flip-box-data-10-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-10-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-10-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-10-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 103, 'style_name' => 'style10', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(70, 81, 82, 0.29)| front-icon-color |#ffffff| front-icon-background-color|#8b00cc| front-heading-color || backend-background-color |rgba(0, 120, 153, 0.41)| backend-icon-color|#000000| backend-info-color |#000000| || || || || || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 235, 235, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| flip-border-radius|5| front-padding-top |10| front-padding-left |10| || front-icon-size |30| front-icon-width |60| front-icon-border-radius |30| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-icon-size |30| backend-icon-width |60| backend-icon-padding-top-bottom |10| backend-icon-padding-left-right |10| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| custom-css |||');
$listdata = Array(
     0 => Array('id' => 3, 'styleid' => 103, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}WooCommerce{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('dog.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.{#}|{#} flip-box-backend-icons{#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('back-girl.jpg') . '{#}|{#}',
      )
);
echo '<input type="hidden" name="oxilab-flip-box-data-10-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-10-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-10-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-10-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';