<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 211, 'style_name' => 'style21', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(255, 255, 255, 0)| front-border-color |#e3e3e3| front-icon-color |#fafafa| front-top-border-color|#ec8206| front-heading-color |#ffffff| backend-background-color |rgba(235, 131, 5, 1)| backend-border-color |#dbdbdb| backend-info-color |#ffffff| backend-button-color |#ec8206| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)||| || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(217, 217, 217, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| front-top-border-height|4| front-icon-size |50| front-icon-width |50| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-col-border-size |1| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |1| flip-backend-border-style |solid| front-icon-padding-top-bottom |0| front-icon-padding-left-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 211, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Mega Icon Box{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('back-girl.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus .{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-21-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-21-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-21-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-21-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 212, 'style_name' => 'style21', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(118, 0, 209, 0.27)| front-border-color |#e3e3e3| front-icon-color |#fafafa| front-top-border-color|#ec067b| front-heading-color |#ffffff| backend-background-color |rgba(236, 6, 123, 1)| backend-border-color |#dbdbdb| backend-info-color |#ffffff| backend-button-color |#ec067b| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(217, 217, 217, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| front-top-border-height|4| front-icon-size |50| front-icon-width |50| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-col-border-size |1| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |1| flip-backend-border-style |solid| front-icon-padding-top-bottom |0| front-icon-padding-left-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 212, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Mega Icon Box{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('dog.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-21-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-21-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-21-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-21-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 213, 'style_name' => 'style21', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(255, 255, 255, 0)| front-border-color |#e3e3e3| front-icon-color |#fafafa| front-top-border-color|#00f7ff| front-heading-color |#ffffff| backend-background-color |rgba(0, 247, 255, 1)| backend-border-color |#dbdbdb| backend-info-color |#424242| backend-button-color |#00f7ff| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(217, 217, 217, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| front-top-border-height|4| front-icon-size |50| front-icon-width |50| || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-col-border-size |1| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |1| flip-backend-border-style |solid| front-icon-padding-top-bottom |0| front-icon-padding-left-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 213, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Mega Icon Box{#}|{#} flip-box-front-icons {#}|{#}fas fa-copyright{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('travel-2.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-21-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-21-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-21-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-21-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
