<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 41, 'style_name' => 'style4', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(131, 9, 224, 0.37)| || front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(134, 9, 224, 1)| || backend-info-color |#ffffff| backend-button-color |#000000| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(125, 67, 240, 1)| front-info-color |#ffffff| backend-title-color |#ffffff| || || || || ||  flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |5| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 232, 232, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |5| || front-icon-size |35| front-icon-width |60| || front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |8| backend-info-margin-right |8| || || flip-border-radius |5| || || front-icon-padding-top-bottom |6| front-icon-padding-left-right |6| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |6| front-info-padding-bottom |6| front-info-padding-left |6| front-info-padding-right |6| backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 41, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Consectetuer Adipiscin{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bug').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('dog.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Far away, behind the word consonantia there live the blind texts n which roasted parts of sentences.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Far away, behind the word consonantia there live the blind texts n which roasted parts of sentences.{#}|{#} flip-box-backend-title {#}|{#}Consectetuer Adipiscin{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-4-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-4-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-4-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-4-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';

echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 42, 'style_name' => 'style4', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeOutBack| front-background-color |rgba(201, 15, 214, 0.83)| || front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(204, 13, 214, 1)| || backend-info-color |#ffffff| backend-button-color |#d600cb| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |#d600cb| front-info-color |#ffffff| backend-title-color |#ffffff| || || || || ||  flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |5| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 232, 232, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |5| || front-icon-size |35| front-icon-width |60| || front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |8| backend-info-margin-right |8| || || flip-border-radius |5| || || front-icon-padding-top-bottom |6| front-icon-padding-left-right |6| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |6| front-info-padding-bottom |6| front-info-padding-left |6| front-info-padding-right |6| backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 42, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Consectetuer Adipiscin{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Far away, behind the word consonantia there live the blind texts n which roasted parts of sentences.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Far away, behind the word consonantia there live the blind texts n which roasted parts of sentences.{#}|{#} flip-box-backend-title {#}|{#}Image Title{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-4-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-4-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-4-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-4-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);


echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 43, 'style_name' => 'style4', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutExpo|front-background-color |rgba(214, 208, 219, 0.67)| || front-icon-color |#2e09e6| || front-heading-color |#262525| backend-background-color |rgba(0, 120, 153, 0.56)| || backend-info-color |#ffffff| backend-button-color |#ffffff| backend-button-background |rgba(36, 34, 34, 1)| backend-button-hover-color |#242222| backend-button-hover-background |rgba(255, 255, 255, 1)| front-info-color |#2e2e2e| backend-title-color |#ffffff|  || || || || ||  flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |5| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 232, 232, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |5| || front-icon-size |35| front-icon-width |60| || front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |8| backend-info-margin-right |8| || || flip-border-radius |5| || || front-icon-padding-top-bottom |6| front-icon-padding-left-right |6| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |6| front-info-padding-bottom |6| front-info-padding-left |6| front-info-padding-right |6| backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 43, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}WooCommerce{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('back-girl.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Far away, behind the word consonantia there live the blind texts n which roasted parts of sentences.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('boy.jpg') . '{#}|{#} flip-box-font-desc {#}|{#}Far away, behind the word consonantia there live the blind texts n which roasted parts of sentences.{#}|{#} flip-box-backend-title {#}|{#}Image Title{#}|{#}',
    )
);
echo '<input type="hidden" name="oxilab-flip-box-data-4-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-4-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-4-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-4-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';