<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 181, 'style_name' => 'style18', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc|front-background-color |rgba(237, 237, 237, 1)| front-border-color|#e3e3e3| backend-border-color|#4e70a6| || front-heading-color |#4e70a6| backend-background-color |rgba(78, 112, 166, 1)| || backend-info-color |#ffffff| backend-button-color |#4e70a6| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(78, 112, 166, 1)| || backend-title-color |#ffffff|file || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(245, 245, 245, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| front-image-height|90| front-padding-top || front-padding-left || || || || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |15| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || flip-col-border-size|0| flip-col-border-style|solid| flip-backend-border-size |2| flip-backend-border-style |solid| || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 181, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}CONTRAST FLIPBOX{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('dog.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}CONTRAST FLIPBOX{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-18-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-18-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-18-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-18-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 182, 'style_name' => 'style18', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(237, 237, 237, 1)| front-border-color|#e3e3e3| backend-border-color|#a64e66| || front-heading-color |#a64e66| backend-background-color |rgba(166, 78, 102, 1)| || backend-info-color |#ffffff| backend-button-color |#a64e66| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(166, 78, 102, 1)| || backend-title-color |#ffffff||| || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(245, 245, 245, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| front-image-height|90| front-padding-top || front-padding-left || || || || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |15| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || flip-col-border-size|0| flip-col-border-style|solid| flip-backend-border-size |2| flip-backend-border-style |solid| || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 182, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}CONTRAST FLIPBOX{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('back-girl.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}CONTRAST FLIPBOX{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-18-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-18-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-18-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-18-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 183, 'style_name' => 'style18', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(237, 237, 237, 1)| front-border-color|#e3e3e3| backend-border-color|#4ea68d| || front-heading-color |#4ea68d| backend-background-color |rgba(78, 166, 141, 1)| || backend-info-color |#ffffff| backend-button-color |#4ea68d| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)| || backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(245, 245, 245, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| front-image-height|90| front-padding-top || front-padding-left || || || || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |15| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || flip-col-border-size|0| flip-col-border-style|solid| flip-backend-border-size |2| flip-backend-border-style |solid| || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 183, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}CONTRAST FLIPBOX{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('travel-2.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}CONTRAST FLIPBOX{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-18-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-18-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-18-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-18-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';