<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 271, 'style_name' => 'style27', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(250, 250, 250, 0.5)| backend-title-bottom-border-color |#ffffff| front-title-bottom-border-color|#ff4242| || front-heading-color |#ff2929| backend-background-color |rgba(160, 118, 44, 1)| front-info-color|#525252| backend-info-color |#e3e3e3| backend-button-color |#a0762c| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(71, 71, 71, 1)| || backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top|10| front-padding-left|10| front-title-border-width|150| front-title-border-height|3| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |20| front-info-padding-bottom |40| front-info-padding-left |6| front-info-padding-right |6| || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |400| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |10| backend-title-border-width |100| backend-title-border-height |3| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |20| front-heding-padding-left |10| front-heding-padding-right |10| || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
     0 => Array('id' => 1, 'styleid' => 271, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Information Flip Boxs{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} flip-box-backend-title {#}|{#}Back Site Content{#}|{#}',
        ),
 );
echo '<input type="hidden" name="oxilab-flip-box-data-27-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-27-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-27-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-27-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 272, 'style_name' => 'style27', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc|  front-background-color |rgba(250, 250, 250, 0.9)| backend-title-bottom-border-color |#ffffff| front-title-bottom-border-color|#007fd4| || front-heading-color |#007fd4| backend-background-color |rgba(0, 124, 212, 0.45)| front-info-color|#525252| backend-info-color |#e3e3e3| backend-button-color |#007fd4| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(71, 71, 71, 1)| || backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top|10| front-padding-left|10| front-title-border-width|150| front-title-border-height|3| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |20| front-info-padding-bottom |40| front-info-padding-left |6| front-info-padding-right |6| || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |400| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |10| backend-title-border-width |100| backend-title-border-height |3| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |20| front-heding-padding-left |10| front-heding-padding-right |10| || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 272, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Information Flip Boxs{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('bg2.png') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('bg2.png') . '{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} flip-box-backend-title {#}|{#}Back Site Content{#}|{#}',
        ),
   );
echo '<input type="hidden" name="oxilab-flip-box-data-27-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-27-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-27-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-27-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 273, 'style_name' => 'style27', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc|  front-background-color |rgba(250, 250, 250, 1)| backend-title-bottom-border-color |#ffffff| front-title-bottom-border-color|#d11bc2| || front-heading-color |#d11bc2| backend-background-color |rgba(209, 27, 194, 1)| front-info-color|#525252| backend-info-color |#e3e3e3| backend-button-color |#d11bc2| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(71, 71, 71, 1)| || backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top|10| front-padding-left|10| front-title-border-width|150| front-title-border-height|3| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |20| front-info-padding-bottom |40| front-info-padding-left |6| front-info-padding-right |6| || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |400| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |10| backend-title-border-width |100| backend-title-border-height |3| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |20| front-heding-padding-left |10| front-heding-padding-right |10| || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
   0 => Array('id' => 3, 'styleid' => 273, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Information Flip Boxs{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} flip-box-backend-title {#}|{#}Back Site Content{#}|{#}',
       )
);
echo '<input type="hidden" name="oxilab-flip-box-data-27-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-27-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-27-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-27-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';