<?php 
if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
 $styledata = Array('id' => 121, 'style_name' => 'style12', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(6, 167, 89, 1)| front-border-color |#e3e4e4| front-icon-color |#06a759| front-icon-background |rgba(255, 255, 255, 1)| front-heading-color |#ffffff| front-info-color |#ffffff| backend-background-color |rgba(224, 224, 224, 0)| backend-border-color |#000000| backend-title-color |#ffffff| backend-title-bottom-border-color |#06a759| backend-info-color |#ffffff| || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(240, 235, 235, 0.72)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| front-icon-height|100| front-icon-size |24| front-icon-width |60| front-icon-border-radius |40| front-heading-size |30| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |6| backend-padding-left |6| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid||||| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |500| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| backend-title-border-width |60| backend-title-border-height |2| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 121, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Background Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('bg2.png') . '{#}|{#} flip-box-backend-desc {#}|{#}It is a long have established fact that a readering is will be by the readable normal distribution let.{#}|{#} {#}|{#}{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('bg2.png') . '{#}|{#} flip-box-font-desc {#}|{#}Bulb Light FlipBox{#}|{#} flip-box-backend-title {#}|{#}Bulb Light FlipBox{#}|{#}',
        ),
     );
echo '<input type="hidden" name="oxilab-flip-box-data-12-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-12-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-12-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-12-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 122, 'style_name' => 'style12', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(255, 162, 0, 1)| front-border-color |#e3e4e4| front-icon-color |#ffa200| front-icon-background |rgba(255, 255, 255, 1)| front-heading-color |#ffffff| front-info-color |#ffffff| backend-background-color |rgba(255, 255, 255, 1)| backend-border-color |#ffa200| backend-title-color |#ffa200| backend-title-bottom-border-color |#ffa200| backend-info-color |#ffa200|    || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(240, 235, 235, 0.72)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| front-icon-height|100| front-icon-size |24| front-icon-width |60| front-icon-border-radius |40| front-heading-size |30| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |6| backend-padding-left |6| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid||||| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |500| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| backend-title-border-width |60| backend-title-border-height |2| custom-css |||');
$listdata = Array(
        0 => Array('id' => 2, 'styleid' => 122, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Background Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}It is a long have established fact that a readering is will be by the readable normal distribution let.{#}|{#} {#}|{#}{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Bulb Light FlipBox{#}|{#} flip-box-backend-title {#}|{#}Bulb Light FlipBox{#}|{#}',
        ),
  );
echo '<input type="hidden" name="oxilab-flip-box-data-12-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-12-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-12-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-12-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 123, 'style_name' => 'style12', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(0, 92, 89, 1)| front-border-color |#ffffff| front-icon-color |#005c59| front-icon-background |rgba(255, 255, 255, 1)| front-heading-color |#ffffff| front-info-color |#ffffff| backend-background-color |rgba(224, 224, 224, 0)| backend-border-color |#a3a3a3| backend-title-color |#ffffff| backend-title-bottom-border-color |#a400ff| backend-info-color |#ffffff|    || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(240, 235, 235, 0.72)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| front-icon-height|100| front-icon-size |24| front-icon-width |60| front-icon-border-radius |40| front-heading-size |30| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |6| backend-padding-left |6| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid||||| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |500| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| backend-title-border-width |60| backend-title-border-height |2| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 123, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Background Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}It is a long have established fact that a readering is will be by the readable normal distribution let.{#}|{#} {#}|{#}{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('bg3.png') . '{#}|{#} flip-box-font-desc {#}|{#}Bulb Light FlipBox{#}|{#} flip-box-backend-title {#}|{#}Bulb Light FlipBox{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-12-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-12-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-12-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-12-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';