<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 91, 'style_name' => 'style9', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(61, 64, 69, 1)| || front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(250, 114, 80, 1)| || backend-info-color |#f2f2f2| backend-button-color |#ffffff| backend-button-background |rgba(61, 64, 69, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(42, 120, 209, 1)| front-icon-background-color|#4b6cf2| backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(222, 222, 222, 0.56)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |25| front-icon-width |60| front-icon-border-radius |40| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |8| front-heding-padding-bottom |8| front-heding-padding-left |8| front-heding-padding-right |8| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |6| backend-info-margin-bottom |6| backend-info-margin-left |6| backend-info-margin-right |6| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 91, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Mini Icon{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Contrary to popular belief, Lorem Ipsum is not simply randoming text. It has roots in a piece of classical Latin literature f BC, McClintock, a Latmpden-Sydney College in ed up one of the more.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}MINI ICON FLIPBOX{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-9-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-9-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-9-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-9-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';

echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 92, 'style_name' => 'style9', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeOutBack| front-background-color |rgba(189, 0, 180, 1)| || front-icon-color |#ffffff| || front-heading-color |#ffffff| backend-background-color |rgba(189, 0, 180, 1)| || backend-info-color |#ffffff| backend-button-color |#ffffff| backend-button-background |rgba(61, 64, 69, 1)| backend-button-hover-color |#3d4045| backend-button-hover-background |rgba(255, 255, 255, 1)| front-icon-background-color|rgba(79, 79, 79, 1)| backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(222, 222, 222, 0.56)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |25| front-icon-width |60| front-icon-border-radius |40| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |8| front-heding-padding-bottom |8| front-heding-padding-left |8| front-heding-padding-right |8| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |6| backend-info-margin-bottom |6| backend-info-margin-left |6| backend-info-margin-right |6| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 92, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Mini Icon{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-copyright').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Contrary to popular belief, Lorem Ipsum is not simply randoming text. It has roots in a piece of classical Latin literature f BC, McClintock, a Latmpden-Sydney College in ed up one of the more{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}MINI ICON FLIPBOX{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-9-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-9-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-9-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-9-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);

echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 93, 'style_name' => 'style9', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(7, 136, 168, 1)| || front-icon-color |#0788a8| || front-heading-color |#ffffff| backend-background-color |rgba(22, 152, 184, 1)| || backend-info-color |#ffffff| backend-button-color |#1698b8| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#1698b8| backend-button-hover-background |rgba(255, 255, 255, 1)| front-icon-background-color|rgba(255, 255, 255, 1)| backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(222, 222, 222, 0.56)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || front-icon-size |25| front-icon-width |60| front-icon-border-radius |40| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |8| front-heding-padding-bottom |8| front-heding-padding-left |8| front-heding-padding-right |8| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |6| backend-info-margin-bottom |6| backend-info-margin-left |6| backend-info-margin-right |6| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| || || || || || || || || || backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 93, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Mini Icon{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Contrary to popular belief, Lorem Ipsum is not simply randoming text. It has roots in a piece of classical Latin literature f BC, McClintock, a Latmpden-Sydney College in ed up one of the more{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}MINI ICON FLIPBOX{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-9-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-9-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-9-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-9-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';