<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 111, 'style_name' => 'style11', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(45, 227, 127, 1)| front-icon-color |#2ee37f| front-icon-background-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(118, 0, 209, 0.75)| backend-title-color |#ffffff| backend-icon-color|#2ee37f| backend-info-color |#ffffff| backend-button-color |#ffffff| backend-button-background |rgba(46, 227, 127, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(89, 104, 186, 1)| || || || || || || ||flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(237, 237, 237, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| flip-border-radius|8| front-padding-top |6| front-padding-left |6| || front-icon-size |26| front-icon-width |60| front-icon-border-radius |6| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |5| backend-padding-left |5| backend-icon-border-bottom|2| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-icon-size |26| backend-icon-width |60| backend-icon-padding-top-bottom |0| backend-icon-padding-left-right |0| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |8| backend-heading-padding-bottom |8| backend-heading-padding-left |8| backend-heading-padding-right |8| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |6| backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |8| backend-info-margin-right |8| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 111, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Border Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Border Flipbox{#}|{#} flip-box-backend-desc {#}|{#}It is a long have established fact that.{#}|{#} flip-box-backend-icons{#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-11-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-11-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-11-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-11-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 112, 'style_name' => 'style11', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc|  front-background-color |rgba(46, 176, 227, 1)| front-icon-color |#2eb0e3| front-icon-background-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(250, 242, 242, 1)| backend-title-color |#1a1a1a| backend-icon-color|#2eb0e3| backend-info-color |#1a1a1a| backend-button-color |#ffffff| backend-button-background |rgba(46, 176, 227, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(89, 104, 186, 1)| || || || || || || ||flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(237, 237, 237, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| flip-border-radius|8| front-padding-top |6| front-padding-left |6| || front-icon-size |26| front-icon-width |60| front-icon-border-radius |6| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |5| backend-padding-left |5| backend-icon-border-bottom|2| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-icon-size |26| backend-icon-width |60| backend-icon-padding-top-bottom |0| backend-icon-padding-left-right |0| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |8| backend-heading-padding-bottom |8| backend-heading-padding-left |8| backend-heading-padding-right |8| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |6| backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |8| backend-info-margin-right |8| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 112, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Border Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Border Flipbox{#}|{#} flip-box-backend-desc {#}|{#}Add backend Info text unless make it blank.{#}|{#} flip-box-backend-icons{#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-11-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-11-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-11-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-11-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 113, 'style_name' => 'style11', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(227, 46, 94, 1)| front-icon-color |#e32e5e| front-icon-background-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(250, 242, 242, 1)| backend-title-color |#2b2b2b| backend-icon-color|#e32e5e| backend-info-color |#292525| backend-button-color |#ffffff| backend-button-background |rgba(227, 46, 94, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(89, 104, 186, 1)| || || || || || || ||flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |320| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(237, 237, 237, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| flip-border-radius|8| front-padding-top |6| front-padding-left |6| || front-icon-size |26| front-icon-width |60| front-icon-border-radius |6| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |5| backend-padding-left |5| backend-icon-border-bottom|2| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |6| backend-info-padding-bottom |6| backend-info-padding-left |6| backend-info-padding-right |6| backend-icon-size |26| backend-icon-width |60| backend-icon-padding-top-bottom |0| backend-icon-padding-left-right |0| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| backend-heading-size |22| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |8| backend-heading-padding-bottom |8| backend-heading-padding-left |8| backend-heading-padding-right |8| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |6| backend-button-text-align |Center| backend-info-margin-top |8| backend-info-margin-bottom |8| backend-info-margin-left |8| backend-info-margin-right |8| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 113, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Border Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Border Flipbox{#}|{#} flip-box-backend-desc {#}|{#}It is a long have established fact that a readering is will be by the readable normal distribution let{#}|{#} flip-box-backend-icons{#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-11-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-11-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-11-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-11-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';