<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 231, 'style_name' => 'style23', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(255, 255, 255, 1)| front-border-color |#f44336| front-icon-color |#ffffff| front-icon-background-color|#f44336| front-heading-color |#f44336| backend-background-color |rgba(244, 67, 54, 1)| backend-info-color |#ffffff| front-info-color |#333333| backend-title-color |#ffffff| backend-border-color |#ffffff| backend-title-bottom-border-color |#ffffff| || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 0.59)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| backend-margin-top-bottom|10| front-padding-top |10| front-padding-left |10| || front-icon-size |46| front-icon-width |74| front-icon-border-radius |50| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |6| front-heding-padding-bottom |6| front-heding-padding-left |6| front-heding-padding-right |6| backend-padding-top |5| backend-padding-left |5| front-margin-top-bottom|10| backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| || || || backend-title-border-width |100| backend-title-border-height |2| || || || || || || || flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |300| backend-heading-text-align |Center| backend-heading-padding-top |20| backend-heading-padding-bottom |8| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 231, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Easy To Customize{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('cogs').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.{#}|{#}{#}|{#}{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} flip-box-backend-title {#}|{#}Easy To Customize{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-23-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-23-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-23-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-23-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 232, 'style_name' => 'style23', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(255, 255, 255, 1)| front-border-color |#9704c4| front-icon-color |#ffffff| front-icon-background-color|#9704c4| front-heading-color |#9704c4| backend-background-color |rgba(151, 4, 196, 1)| backend-info-color |#ffffff| front-info-color |#575757| backend-title-color |#ffffff| backend-border-color |#ffffff| backend-title-bottom-border-color |#ffffff||| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 0.59)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| backend-margin-top-bottom|10| front-padding-top |10| front-padding-left |10| || front-icon-size |46| front-icon-width |74| front-icon-border-radius |50| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |6| front-heding-padding-bottom |6| front-heding-padding-left |6| front-heding-padding-right |6| backend-padding-top |5| backend-padding-left |5| front-margin-top-bottom|10| backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| || || || backend-title-border-width |100| backend-title-border-height |2| || || || || || || || flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |300| backend-heading-text-align |Center| backend-heading-padding-top |20| backend-heading-padding-bottom |8| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 232, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Bug and Error Free{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bug').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient mont{#}|{#}{#}|{#}{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit.{#}|{#} flip-box-backend-title {#}|{#}Bug and Error Free{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-23-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-23-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-23-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-23-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 233, 'style_name' => 'style23', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(255, 255, 255, 1)| front-border-color |#009e79| front-icon-color |#ffffff| front-icon-background-color|#009e79| front-heading-color |#009e79| backend-background-color |rgba(0, 158, 121, 1)| backend-info-color |#ffffff| front-info-color |#333333| backend-title-color |#ffffff| backend-border-color |#ffffff| backend-title-bottom-border-color |#ffffff| || || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(209, 201, 201, 0.59)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| backend-margin-top-bottom|10| front-padding-top |10| front-padding-left |10| || front-icon-size |46| front-icon-width |74| front-icon-border-radius |50| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |6| front-heding-padding-bottom |6| front-heding-padding-left |6| front-heding-padding-right |6| backend-padding-top |5| backend-padding-left |5| front-margin-top-bottom|10| backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| || || || backend-title-border-width |100| backend-title-border-height |2| || || || || || || || flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid| front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |300| backend-heading-text-align |Center| backend-heading-padding-top |20| backend-heading-padding-bottom |8| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 233, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}User Friendly{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('users').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.{#}|{#}{#}|{#}{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetur adipiscing elit{#}|{#} flip-box-backend-title {#}|{#}User Friendly{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-23-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-23-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-23-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-23-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
