<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 51, 'style_name' => 'style5', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(145, 44, 222, 0)| || || || || backend-background-color |rgba(246, 36, 89, 1)| || backend-info-color |#ffffff| backend-button-color |#f0f0f0| backend-button-background |rgba(26, 26, 26, 1)| backend-button-hover-color |#1a1a1a| backend-button-hover-background |rgba(240, 240, 240, 1)| || backend-title-color |#ffffff| ) || || || || || flip-col |oxilab-flip-box-col-1| flip-width |282| flip-height |330| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 235, 235, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || || || || || || || || || || backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |8| backend-heading-padding-bottom |8| backend-heading-padding-left |8| backend-heading-padding-right |8| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 51, 'title' => '',
        'files' => '{#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('boy.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Far away, behind the word consonantia there live the blind texts n which roasted parts of sentences.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Consectetuer Adipiscin{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-5-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-5-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-5-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-5-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';

echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 52, 'style_name' => 'style5', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutExpo| front-background-color |rgba(145, 44, 222, 0)| || || || || backend-background-color |rgba(0, 0, 0, 1)| || backend-info-color |#ffffff| backend-button-color |#ffffff| backend-button-background |rgba(214, 23, 166, 1)| backend-button-hover-color |#d617a6| backend-button-hover-background |rgba(255, 255, 255, 1)| || backend-title-color |#ffffff|  || || || || || flip-col |oxilab-flip-box-col-1| flip-width |282| flip-height |330| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 235, 235, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || || || || || || || || || || backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |8| backend-heading-padding-bottom |8| backend-heading-padding-left |8| backend-heading-padding-right |8| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 52, 'title' => '',
        'files' => '{#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('dog.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Flip Animation{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-5-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-5-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-5-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-5-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);


echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 53, 'style_name' => 'style5', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeOutBack| front-background-color |rgba(145, 44, 222, 0)| || || || || backend-background-color |rgba(246, 36, 89, 1)| || backend-info-color |#ffffff| backend-button-color |#ffffff| backend-button-background |rgba(26, 26, 26, 1)| backend-button-hover-color |#1a1a1a| backend-button-hover-background |rgba(255, 255, 255, 1)| || backend-title-color |#ffffff| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |282| flip-height |330| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(235, 235, 235, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| || || || || || || || || || || || || || backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |8| backend-heading-padding-bottom |8| backend-heading-padding-left |8| backend-heading-padding-right |8| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 53, 'title' => '',
        'files' => '{#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('back-girl.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Flip Animation{#}|{#}',
    )
);
echo '<input type="hidden" name="oxilab-flip-box-data-5-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-5-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-5-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-5-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
