<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 151, 'style_name' => 'style15', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc|  front-background-color |rgba(61, 90, 254, 1)| front-border-color |#55c7dc| front-heading-color |#ffffff| front-info-color |#ffffff| backend-background-color |rgba(193, 185, 212, 0.29)| backend-border-color |#55c7dc| front-title-bottom-border-color |#55c7dc| backend-button-color |#ffffff| backend-button-background |rgba(61, 90, 254, 1)| backend-button-hover-color |#3d5afe| backend-button-hover-background |#ffffff| backend-icon-color |#3d5afe||| || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(242, 242, 242, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || || || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |700| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| backend-icon-size |60| backend-icon-width|60| backend-icon-padding-top-bottom|10| backend-icon-padding-left-right|10| || || || || || || flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid| || || front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |400| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| front-title-border-width |60| front-title-border-height |2| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 151, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Material Flipbox{#}|{#} flip-box-backend-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('pic1.png') . '{#}|{#} flip-box-font-desc {#}|{#}It is a long have established fact that a readering is will be by the readable normal distribution letters...{#}|{#} {#}|{#}{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-15-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-15-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-15-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-15-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 152, 'style_name' => 'style15', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutCirc|  front-background-color |rgba(145, 20, 161, 1)| front-border-color |#cc1be0| front-heading-color |#ffffff| front-info-color |#ffffff| backend-background-color |rgba(255, 255, 255, 0.24)| backend-border-color |#cc1be0| front-title-bottom-border-color |#cc1be0| backend-button-color |#ffffff| backend-button-background |rgba(204, 27, 224, 1)| backend-button-hover-color |#cc1be0| backend-button-hover-background |#ffffff| backend-icon-color |#cc1be0| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(242, 242, 242, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || || || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |700| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| backend-icon-size |60| backend-icon-width|60| backend-icon-padding-top-bottom|10| backend-icon-padding-left-right|10| || || || || || || flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid| || || front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |400| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| front-title-border-width |60| front-title-border-height |2| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| custom-css |||');

$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 152, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Material Flipbox{#}|{#} flip-box-backend-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('pic1.png') . '{#}|{#} flip-box-font-desc {#}|{#}It is a long have established fact that a readering is will be by the readable normal distribution letters...{#}|{#} {#}|{#}{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-15-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-15-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-15-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-15-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 153, 'style_name' => 'style15', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc|  front-background-color |rgba(21, 104, 140, 1)| front-border-color |#55c7dc| front-heading-color |#ffffff| front-info-color |#ffffff| backend-background-color |rgba(21, 100, 140, 0.29)| backend-border-color |#55c7dc| front-title-bottom-border-color |#55c7dc| backend-button-color |#ffffff| backend-button-background |rgba(21, 104, 140, 1)| backend-button-hover-color |#15688c| backend-button-hover-background |#ffffff| backend-icon-color |#15688c||| || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(242, 242, 242, 0.52)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |10| front-padding-left |10| || || || || front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |700| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |10| backend-padding-left |10| backend-icon-size |60| backend-icon-width|60| backend-icon-padding-top-bottom|10| backend-icon-padding-left-right|10| || || || || || || flip-col-border-size |2| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |2| flip-backend-border-style |solid| || || front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |400| front-info-text-align |Center| front-info-padding-top |10| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| front-title-border-width |60| front-title-border-height |2| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 153, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Material Flipbox{#}|{#} flip-box-backend-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('pic1.png') . '{#}|{#} flip-box-font-desc {#}|{#}It is a long have established fact that a readering is will be by the readable normal distribution letters...{#}|{#} {#}|{#}{#}|{#}',
    )
);
echo '<input type="hidden" name="oxilab-flip-box-data-15-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-15-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-15-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-15-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';