<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 221, 'style_name' => 'style22', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(118, 0, 209, 0)| backend-title-bottom-border-color |#e3e3e3| || || || backend-background-color |rgba(0, 115, 153, 1)| || backend-info-color |#ffffff| backend-button-color |#007399| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(0, 115, 153, 1)| || backend-title-color |#ffffff||| || || || || flip-col |oxilab-flip-box-col-1| flip-width |262| flip-height |262| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(209, 201, 201, 0.63)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |9| backend-info-padding-bottom |0| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |13| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| backend-title-border-width |60| backend-title-border-height |3| || || || || || || || || || || || backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 221, 'title' => '',
        'files' => '{#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('1.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Consectetuer Adipiscin{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-22-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-22-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-22-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-22-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 222, 'style_name' => 'style22', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(118, 0, 209, 0)| backend-title-bottom-border-color |#e3e3e3| || || || backend-background-color |rgba(27, 199, 18, 1)| || backend-info-color |#ffffff| backend-button-color |#1bc712| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)| || backend-title-color |#ffffff||| || || || || flip-col |oxilab-flip-box-col-1| flip-width |262| flip-height |262| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(209, 201, 201, 0.63)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |9| backend-info-padding-bottom |0| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |13| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| backend-title-border-width |60| backend-title-border-height |3| || || || || || || || || || || || backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 222, 'title' => '',
        'files' => '{#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('boy.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Lorem ipsum{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-22-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-22-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-22-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-22-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 223, 'style_name' => 'style22', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(118, 0, 209, 0)| backend-title-bottom-border-color |#e3e3e3| || || || backend-background-color |rgba(114, 201, 0, 0.13)| || backend-info-color |#ffffff| backend-button-color |#72c900| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#72c900| backend-button-hover-background |rgba(255, 255, 255, 1)| || backend-title-color |#ffffff||| || || || || flip-col |oxilab-flip-box-col-1| flip-width |262| flip-height |262| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(209, 201, 201, 0.63)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || || || || || || || || || || || || || || || || backend-padding-top |10| backend-padding-left |10| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |9| backend-info-padding-bottom |0| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |13| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| || || flip-border-radius |5| backend-title-border-width |60| backend-title-border-height |3| || || || || || || || || || || || backend-heading-size |18| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 223, 'title' => '',
        'files' => ' {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('watch.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('bg2.png') . '{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}voluptatem{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-22-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-22-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-22-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-22-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';