<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 241, 'style_name' => 'style24', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(255, 255, 255, 1)| front-border-color |#f44336| front-icon-color |#ffffff| front-icon-background-color|#f44336| front-heading-color |#f44336| backend-background-color |rgba(244, 67, 54, 1)| backend-info-color |#ffffff| front-info-color |#333333| backend-title-color |#ffffff| backend-border-color |#cccccc| backend-icon-color |#f44336| backend-icon-background-color|rgba(255, 255, 255, 1)| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(209, 201, 201, 0.73)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| || front-icon-size |25| || front-icon-border-radius |10| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |12| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |6| backend-padding-left |6| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |100| backend-info-text-align |Center| backend-info-padding-top |5| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| || || || || || || backend-icon-size |25| backend-icon-border-radius |10| backend-icon-padding-top-bottom |8| backend-icon-padding-left-right |10| || || flip-col-border-size |1| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |1| flip-backend-border-style |solid| front-icon-padding-top-bottom |8| front-icon-padding-left-right |10| front-info-size |14| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |2| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |5| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 241, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Bug and Error Free{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bug').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.{#}|{#} flip-box-backend-icons {#}|{#}'. FlipBoxesImageAdFAData('cogs').'{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.{#}|{#} flip-box-backend-title {#}|{#}Easy To Customize{#}|{#}',
       ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-24-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-24-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-24-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-24-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 242, 'style_name' => 'style24', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutExpo| front-background-color |rgba(255, 255, 255, 1)| front-border-color |#d11bc2| front-icon-color |#ffffff| front-icon-background-color|#d11bc2| front-heading-color |#d11bc2| backend-background-color |rgba(209, 27, 194, 1)| backend-info-color |#ffffff| front-info-color |#333333| backend-title-color |#ffffff| backend-border-color |#cccccc| backend-icon-color |#d11bc2| backend-icon-background-color|rgba(255, 255, 255, 1)| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(209, 201, 201, 0.73)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| || front-icon-size |25| || front-icon-border-radius |10| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |12| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |6| backend-padding-left |6| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |100| backend-info-text-align |Center| backend-info-padding-top |5| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| || || || || || || backend-icon-size |25| backend-icon-border-radius |10| backend-icon-padding-top-bottom |8| backend-icon-padding-left-right |10| || || flip-col-border-size |1| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |1| flip-backend-border-style |solid| front-icon-padding-top-bottom |8| front-icon-padding-left-right |10| front-info-size |14| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |2| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |5| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 242, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}User Friendly{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('users').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.{#}|{#} flip-box-backend-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bug').'{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.{#}|{#} flip-box-backend-title {#}|{#}Bug and Error Free{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-24-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-24-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-24-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-24-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 243, 'style_name' => 'style24', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeOutBack| front-background-color |rgba(255, 255, 255, 1)| front-border-color |#007fd4| front-icon-color |#ffffff| front-icon-background-color|#007fd4| front-heading-color |#007fd4| backend-background-color |rgba(0, 127, 212, 1)| backend-info-color |#ffffff| front-info-color |#333333| backend-title-color |#ffffff| backend-border-color |#cccccc| backend-icon-color |#007fd4| backend-icon-background-color|rgba(255, 255, 255, 1)| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |300| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |1.2| flip-boxshow-color |rgba(209, 201, 201, 0.73)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| || front-icon-size |25| || front-icon-border-radius |10| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |12| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| backend-padding-top |6| backend-padding-left |6| || backend-info-size |14| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |100| backend-info-text-align |Center| backend-info-padding-top |5| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| || || || || || || backend-icon-size |25| backend-icon-border-radius |10| backend-icon-padding-top-bottom |8| backend-icon-padding-left-right |10| || || flip-col-border-size |1| flip-col-border-style |solid| flip-border-radius |5| flip-backend-border-size |1| flip-backend-border-style |solid| front-icon-padding-top-bottom |8| front-icon-padding-left-right |10| front-info-size |14| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |2| front-info-padding-bottom |10| front-info-padding-left |10| front-info-padding-right |10| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |5| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 243, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}Cross browser{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('cogs').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.{#}|{#} flip-box-backend-icons {#}|{#}'. FlipBoxesImageAdFAData('cogs').'{#}|{#} flip-box-backend-link {#}|{#}{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.{#}|{#} flip-box-backend-title {#}|{#}Easy To Customize{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-24-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-24-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-24-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-24-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';