<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 261, 'style_name' => 'style26', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(92, 75, 82, 1)| backend-title-bottom-border-color |#ffffff| front-border-color|#ffffff| front-number-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(76, 78, 115, 1)| backend-border-color|#ffffff| backend-info-color |#e3e3e3| backend-button-color |#4c4e73| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(27, 107, 84, 1)| || backend-title-color |#ffffff||| || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(194, 194, 194, 0.64)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| front-border-margin-top|8| front-padding-top|10| front-padding-left|10| flip-front-border-size|3| flip-front-border-style|solid| front-number-size|35| front-number-family|Open+Sans| front-number-style|normal| front-number-weight|600| front-number-padding-top-bottom|10| front-number-padding-left-right|10| || || || || || backend-padding-top |10| backend-padding-left |10| backend-border-margin-top|8| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-backend-border-size |2| flip-backend-border-style |solid| flip-border-radius |10| backend-title-border-width |100| backend-title-border-height |3| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 261, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Consectetuer Adipiscin{#}|{#} flip-box-front-icons {#}|{#}1{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Consectetuer Adipiscin{#}|{#}',
       ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-26-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-26-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-26-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-26-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 262, 'style_name' => 'style26', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(76, 78, 115, 1)| backend-title-bottom-border-color |#ffffff| front-border-color|#ffffff| front-number-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(160, 118, 44, 1)| backend-border-color|#ffffff| backend-info-color |#ffffff| backend-button-color |#a0762c| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(117, 72, 166, 1)| || backend-title-color |#ffffff||| || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(194, 194, 194, 0.64)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| front-border-margin-top|8| front-padding-top|10| front-padding-left|10| flip-front-border-size|3| flip-front-border-style|solid| front-number-size|35| front-number-family|Open+Sans| front-number-style|normal| front-number-weight|600| front-number-padding-top-bottom|10| front-number-padding-left-right|10| || || || || || backend-padding-top |10| backend-padding-left |10| backend-border-margin-top|8| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-backend-border-size |2| flip-backend-border-style |solid| flip-border-radius |10| backend-title-border-width |100| backend-title-border-height |3| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 262, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Consectetuer Adipiscin{#}|{#} flip-box-front-icons {#}|{#}2{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Consectetuer Adipiscin{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-26-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-26-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-26-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-26-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 263, 'style_name' => 'style26', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(115, 48, 68, 1)| backend-title-bottom-border-color |#ffffff| front-border-color|#ffffff| front-number-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(160, 118, 44, 1)| backend-border-color|#ffffff| backend-info-color |#ffffff| backend-button-color |#a0762c| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(71, 71, 71, 1)| || backend-title-color |#ffffff||| || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |280| margin-top |10| margin-left |10| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(194, 194, 194, 0.64)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| front-border-margin-top|8| front-padding-top|10| front-padding-left|10| flip-front-border-size|3| flip-front-border-style|solid| front-number-size|35| front-number-family|Open+Sans| front-number-style|normal| front-number-weight|600| front-number-padding-top-bottom|10| front-number-padding-left-right|10| || || || || || backend-padding-top |10| backend-padding-left |10| backend-border-margin-top|8| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |10| backend-info-padding-bottom |10| backend-info-padding-left |10| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |10| backend-info-margin-bottom |10| backend-info-margin-left |10| backend-info-margin-right |10| flip-backend-border-size |2| flip-backend-border-style |solid| flip-border-radius |10| backend-title-border-width |100| backend-title-border-height |3| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |10| front-heding-padding-left |10| front-heding-padding-right |10| || || backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |10| backend-heading-padding-bottom |10| backend-heading-padding-left |10| backend-heading-padding-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 263, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Consectetuer Adipiscin{#}|{#} flip-box-front-icons {#}|{#}3{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} {#}|{#}{#}|{#} flip-box-backend-title {#}|{#}Consectetuer Adipiscin{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-26-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-26-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-26-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-26-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';