<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 11, 'style_name' => 'style1', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(0, 120, 153, 1)| front-border-color |#e3e3e3| front-icon-color |#8b00cc| front-icon-background |rgba(255, 255, 255, 1)| front-heading-color |#ffffff| backend-background-color |rgba(0, 120, 153, 1)| backend-border-color |#dbdbdb| backend-info-color |#ffffff| backend-button-color |#d600cb| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)|  || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |330| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(217, 217, 217, 0.73)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| front-image-height |85| front-padding-top |7| front-padding-left |7| front-border-size |3| front-icon-size |20| front-icon-width |60| front-icon-border-radius |60| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |20| front-heding-padding-left |20| front-heding-padding-right |20| backend-padding-top |20| backend-padding-left |20| backend-border-size |3| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |15| backend-info-padding-bottom |20| backend-info-padding-left |20| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-padding-top |10| backend-button-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |20| backend-info-margin-bottom |20| backend-info-margin-left |10| backend-info-margin-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 11, 'title' => '',
        'files' => ' flip-box-front-title {#}|{#}WooCommerce{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('1.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-1-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-1-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-1-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-1-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';


echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 12, 'style_name' => 'style1', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-bottom-to-top| oxilab-flip-effects |easing_easeOutBack| front-background-color |rgba(92, 75, 82, 1)| front-border-color |#e3e3e3| front-icon-color |#5c4b52| front-icon-background |rgba(255, 255, 255, 1)| front-heading-color |#ffffff| backend-background-color |rgba(0, 120, 153, 0.41)| backend-border-color |#dbdbdb| backend-info-color |#ffffff| backend-button-color |#d600cb| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |330| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(217, 217, 217, 0.73)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| front-image-height |85| front-padding-top |7| front-padding-left |7| front-border-size |3| front-icon-size |20| front-icon-width |60| front-icon-border-radius |60| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |20| front-heding-padding-left |20| front-heding-padding-right |20| backend-padding-top |20| backend-padding-left |20| backend-border-size |3| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |15| backend-info-padding-bottom |20| backend-info-padding-left |20| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-padding-top |10| backend-button-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |20| backend-info-margin-bottom |20| backend-info-margin-left |10| backend-info-margin-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 12, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Image Icon Box{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-balance-scale').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('dog.jpg') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}' . oxilab_flip_box_admin_image('bg2.png') . '{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-1-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-1-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-1-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-1-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);


echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 13, 'style_name' => 'style1', 'css' => ' oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeOutBack| front-background-color |rgba(76, 78, 115, 1)| front-border-color |#e3e3e3| front-icon-color |#4c4e73| front-icon-background |rgba(255, 255, 255, 1)| front-heading-color |#ffffff| backend-background-color |rgba(76, 78, 115, 1)| backend-border-color |#dbdbdb| backend-info-color |#ffffff| backend-button-color |#d600cb| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(214, 0, 203, 1)| || || || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |330| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(217, 217, 217, 0.73)| flip-boxshow-horizontal |0| flip-boxshow-vertical |2| flip-boxshow-blur |8| flip-boxshow-spread |0| front-image-height |85| front-padding-top |7| front-padding-left |7| front-border-size |3| front-icon-size |20| front-icon-width |60| front-icon-border-radius |60| front-heading-size |20| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |10| front-heding-padding-bottom |20| front-heding-padding-left |20| front-heding-padding-right |20| backend-padding-top |20| backend-padding-left |20| backend-border-size |3| backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |15| backend-info-padding-bottom |20| backend-info-padding-left |20| backend-info-padding-right |10| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-padding-top |10| backend-button-padding-left |20| backend-button-border-radius |40| backend-button-text-align |Center| backend-info-margin-top |20| backend-info-margin-bottom |20| backend-info-margin-left |10| backend-info-margin-right |10| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 13, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Consectetuer{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('fa-bandcamp').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}' . oxilab_flip_box_admin_image('bg1.png') . '{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#}',
    ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-1-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-1-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-1-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-1-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';

/*
echo '|| || || || || || ||  || || || || || || || || || || || || || || ';
 * 
 */