<?php

if (!defined('ABSPATH'))
    exit;
oxilab_flip_box_user_capabilities();
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 131, 'style_name' => 'style13', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-left-to-right| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(41, 219, 100, 1)| front-icon-border-color|#ffffff| front-icon-color |#2bda63| front-icon-background-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(238, 238, 238, 1)| || backend-info-color |#6b6b6b| backend-button-color |#2bda63| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(43, 218, 99, 1)| front-info-color |#ffffff| backend-title-color |#080808|    || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |240| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(255, 255, 255, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| || front-icon-size |24| front-icon-width |60| front-icon-border-radius |40| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |6| front-heding-padding-bottom |6| front-heding-padding-left |6| front-heding-padding-right |6| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |5| backend-info-padding-bottom |5| backend-info-padding-left |5| backend-info-padding-right |5| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |6| backend-info-margin-bottom |6| backend-info-margin-left |6| backend-info-margin-right |6| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |6| front-info-padding-bottom |6| front-info-padding-left |6| front-info-padding-right |6| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |5| backend-heading-padding-bottom |5| backend-heading-padding-left |5| backend-heading-padding-right |5| custom-css |||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 131, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Normal Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}It is a long established fact that reader will be distracted.{#}|{#} flip-box-backend-button-text {#}|{#}Read More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet{#}|{#} flip-box-backend-title {#}|{#}Orange Bicycle{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-13-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-13-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-13-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-13-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 132, 'style_name' => 'style13', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-top-to-bottom| oxilab-flip-effects |easing_easeInOutCirc| front-background-color |rgba(150, 105, 226, 1)| front-icon-border-color|#ffffff| front-icon-color |#9669e2| front-icon-background-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(238, 238, 238, 1)| || backend-info-color |#6b6b6b| backend-button-color |#9669e2| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(150, 105, 226, 1)| front-info-color |#ffffff| backend-title-color |#080808| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |240| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(255, 255, 255, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| || front-icon-size |24| front-icon-width |60| front-icon-border-radius |40| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |6| front-heding-padding-bottom |6| front-heding-padding-left |6| front-heding-padding-right |6| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |5| backend-info-padding-bottom |5| backend-info-padding-left |5| backend-info-padding-right |5| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |6| backend-info-margin-bottom |6| backend-info-margin-left |6| backend-info-margin-right |6| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |6| front-info-padding-bottom |6| front-info-padding-left |6| front-info-padding-right |6| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |5| backend-heading-padding-bottom |5| backend-heading-padding-left |5| backend-heading-padding-right |5| custom-css |||');
$listdata = Array(
    0 => Array('id' => 2, 'styleid' => 132, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Normal Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor{#}|{#} flip-box-backend-button-text {#}|{#}Read More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet{#}|{#} flip-box-backend-title {#}|{#}The Dummy{#}|{#}',
        ),
);
echo '<input type="hidden" name="oxilab-flip-box-data-13-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-13-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-13-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-13-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';
echo '<div class="oxilab-flip-box-col-3">';
$styledata = Array('id' => 133, 'style_name' => 'style13', 'css' => 'oxilab-flip-type |oxilab-flip-box-flip oxilab-flip-box-flip-right-to-left| oxilab-flip-effects |easing_easeInOutExpo|  front-background-color |rgba(240, 97, 56, 1)| front-icon-border-color|#ffffff| front-icon-color |#f06138| front-icon-background-color|#ffffff| front-heading-color |#ffffff| backend-background-color |rgba(238, 238, 238, 1)| || backend-info-color |#6b6b6b| backend-button-color |#f06138| backend-button-background |rgba(255, 255, 255, 1)| backend-button-hover-color |#ffffff| backend-button-hover-background |rgba(240, 97, 56, 1)| front-info-color |#ffffff| backend-title-color |#080808| || || || || || flip-col |oxilab-flip-box-col-1| flip-width |280| flip-height |240| margin-top |10| margin-left |20| flip-open-tabs || oxilab-animation || animation-duration |2| flip-boxshow-color |rgba(255, 255, 255, 1)| flip-boxshow-horizontal |0| flip-boxshow-vertical |0| flip-boxshow-blur |6| flip-boxshow-spread |0| || front-padding-top |6| front-padding-left |6| || front-icon-size |24| front-icon-width |60| front-icon-border-radius |40| front-heading-size |22| front-heading-family |Open+Sans| front-heding-style |normal| front-heding-weight |600| front-heding-text-align |Center| front-heding-padding-top |6| front-heding-padding-bottom |6| front-heding-padding-left |6| front-heding-padding-right |6| backend-padding-top |10| backend-padding-left |10| || backend-info-size |16| backend-info-family |Open+Sans| backend-info-style |normal| backend-info-weight |300| backend-info-text-align |Center| backend-info-padding-top |5| backend-info-padding-bottom |5| backend-info-padding-left |5| backend-info-padding-right |5| backend-button-size |14| backend-button-family |Open+Sans| backend-button-style |normal| backend-button-weight |300| backend-button-info-padding-top|10| backend-button-info-padding-left |20| backend-button-border-radius |30| backend-button-text-align |Center| backend-info-margin-top |6| backend-info-margin-bottom |6| backend-info-margin-left |6| backend-info-margin-right |6| || || flip-border-radius |5| || || front-icon-padding-top-bottom |10| front-icon-padding-left-right |10| front-info-size |16| front-info-family |Open+Sans| front-info-style |normal| front-info-weight |300| front-info-text-align |Center| front-info-padding-top |6| front-info-padding-bottom |6| front-info-padding-left |6| front-info-padding-right |6| backend-heading-size |20| backend-heading-family |Open+Sans| backend-heading-style |normal| backend-heading-weight |600| backend-heading-text-align |Center| backend-heading-padding-top |5| backend-heading-padding-bottom |5| backend-heading-padding-left |5| backend-heading-padding-right |5| custom-css |||');
$listdata = Array(
    0 => Array('id' => 3, 'styleid' => 133, 'title' => '',
        'files' => 'flip-box-front-title {#}|{#}Normal Flipbox{#}|{#} flip-box-front-icons {#}|{#}'. FlipBoxesImageAdFAData('facebook').'{#}|{#} flip-box-image-upload-url-01 {#}|{#}{#}|{#} flip-box-backend-desc {#}|{#}Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.{#}|{#} flip-box-backend-button-text {#}|{#}Learn More{#}|{#} flip-box-backend-link {#}|{#}#{#}|{#} flip-box-image-upload-url-02 {#}|{#}{#}|{#} flip-box-font-desc {#}|{#}Lorem ipsum dolor sit amet{#}|{#} flip-box-backend-title {#}|{#}Orange Bicycle{#}|{#}',
        )
);
echo '<input type="hidden" name="oxilab-flip-box-data-13-' . $listdata[0]['id'] . '" id="oxilab-flip-box-data-13-' . $listdata[0]['id'] . '" value="' . $styledata['css'] . '">';
echo '<input type="hidden" name="oxilab-flip-box-files-13-' . $listdata[0]['id'] . '" id="oxilab-flip-box-files-13-' . $listdata[0]['id'] . '" value="' . $listdata[0]['files'] . '">';
echo oxilab_flipbox_admin_style_layouts($styledata, $listdata);
echo '</div>';