# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
  - 5.5

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (or "latest")
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit

# Reduce mail notifications by Travis CI to a minimum
notifications:
  email:
    on_success: change
    on_failure: always
